In [18]:
import pandas as pd
import seaborn as sns

titanic_df = pd.read_csv(
    r"C:\Users\shahh\OneDrive\Desktop\Data Science And Machine Learning\Skill_Sikshya\Day22\titanic_data.csv",
    delimiter = ",",
    header = 0
    )

titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Chi-Square Test
The Chi-Square Test (χ²) is used to determine whether there is a significant relationship between categorical variables by comparing observed and expected frequencies.

Formula:

$$ \chi^2 = \sum \frac{(O-E)^2}{E} $$

Where:

O = Observed frequency
E = Expected frequency
χ² = Chi-square statistic

A small p-value (typically < 0.05) indicates a statistically significant relationship.

In [19]:
import scipy.stats as stats

In [20]:
contengency_table = pd.crosstab(titanic_df.Pclass, titanic_df.Survived)
contengency_table

Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

In [21]:
chi2_score, pvalue, dof, excepted_frquency = stats.chi2_contingency(contingency_table)

In [22]:
print(f"Chi-Squared test score = {round(chi2_score, 3)}")
print(f"p-value = {round(pvalue, 5)}")
pvalue < 0.05

Chi-Squared test score = 102.889
p-value = 0.0

np.True_

In [23]:
contengency_table = pd.crosstab(titanic_df.Cabin, titanic_df.Parch)
contengency_table

Parch  0  1  2  4
Cabin
A10    1  0  0  0
A14    1  0  0  0
A16    1  0  0  0
A19    1  0  0  0
A20    1  0  0  0
...   .. .. .. ..
F33    3  0  0  0
F38    1  0  0  0
F4     0  2  0  0
G6     0  3  1  0
T      1  0  0  0

[147 rows x 4 columns]

In [24]:
chi2_score, pvalue,  _, _ = stats.chi2_contingency(contengency_table)

In [25]:
print(f"Chi-Squared test score = {round(chi2_score, 3)}")
print(f"p-value = {round(pvalue, 5)}")
pvalue < 0.05

Chi-Squared test score = 415.306
p-value = 0.77571

np.False_